# Generated by Django 2.2.6 on 2019-10-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Union_name', models.CharField(max_length=50)),
                ('Upazil_name', models.CharField(max_length=50)),
                ('District_name', models.CharField(max_length=50)),
                ('Division_name', models.CharField(max_length=50)),
            ],
        ),
    ]
