# Generated by Django 2.2.6 on 2019-11-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BirthRegisterSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='Upazil_name',
            new_name='Upazila_name',
        ),
    ]
