# Generated by Django 2.2.6 on 2019-11-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirthRegisterSystem', '0002_auto_20191128_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_name', models.CharField(max_length=50)),
                ('District_name', models.CharField(max_length=50)),
                ('Division_name', models.CharField(max_length=50)),
                ('Upazila_name', models.CharField(max_length=50)),
                ('Union_name', models.CharField(max_length=50)),
                ('H_username', models.CharField(max_length=50)),
                ('H_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UpAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_name', models.CharField(max_length=50)),
                ('Division_name', models.CharField(max_length=50)),
                ('Upazila_name', models.CharField(max_length=50)),
                ('U_username', models.CharField(max_length=50)),
                ('U_password', models.CharField(max_length=50)),
            ],
        ),
    ]
