# Generated by Django 2.2.6 on 2019-12-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewChildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Blood_group', models.CharField(max_length=10)),
                ('Father_name', models.CharField(max_length=50)),
                ('Father_NID', models.CharField(max_length=20)),
                ('Mother_name', models.CharField(max_length=50)),
                ('Religion', models.CharField(max_length=20)),
                ('District_name', models.CharField(max_length=50)),
                ('Division_name', models.CharField(max_length=50)),
                ('Upazila_name', models.CharField(max_length=50)),
                ('Union_name', models.CharField(max_length=50)),
            ],
        ),
    ]
